name: Android CI

on:
  pull_request:

env:
  APP_DIR: ./client

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Mvoe dir to Application directory
      run: cd ${{env.APP_DIR}}
    - name: Build
      run: ./gradlew :androidApp:assembleDebug
